### ISSUE TITLE
PREFIX causes add_subdirectories() to fail

### ISSUE THREAD

**Issue by zfields** [Crascit/DownloadProject#23] opened 2017-03-21 05:22 UTC
`add_subdirectory given source "<prefix>/<PROJ>-src" which is not an
  existing directory.`

**Comment by audiofanatic** [comment] 2017-03-21 05:27
Can you provide a complete example that reproduces the problem? There's not enough in that single line of output for me to have much of an idea what could be going wrong.

**Comment by zfields** [comment] 2017-03-21 06:44
```
include(DownloadProject.cmake)

# Download Serial Wiring as source
download_project(
  PROJ serial_wiring
  PREFIX external <------------------------------------------------------------THIS LINE BREAKS THE MODULE
  GIT_REPOSITORY https://github.com/remote-wiring/serial-wiring.git
  GIT_TAG master
  TIMEOUT 10
)
add_subdirectory(${serial_wiring_SOURCE_DIR} ${serial_wiring_BINARY_DIR})
```

**Comment by zfields** [comment] 2017-03-21 06:45
You can check the [source](https://github.com/remote-wiring/remote-wiring)

**Comment by audiofanatic** [comment] 2017-03-21 08:14
Thanks for the extra info. I can now reproduce your problem. It is due to the supplied prefix being a relative path instead of an absolute one. This should be okay, but the values of `serial_wiring_SOURCE_DIR` and `serial_wiring_BINARY_DIR` are not being forced to be absolute paths like they should be. I'll push a fix shortly after it's been tested.

**Comment by audiofanatic** [comment] 2017-03-21 08:38
Fixed on master. Thanks for reporting and glad you found it useful.

**Closed by audiofanatic** 2017-03-21 08:38 UTC
